### ISSUE TITLE
Import complet du package.json

### ISSUE THREAD

**Issue by valdoryu** [guillaumeduhan/vue-bootstrap-boilerplate#3]
https://github.com/guillaumeduhan/vue-bootstrap-boilerplate/blob/e153c1de9bf07985e3d26e508ccf51caf4272dbc/src/views/Home.vue#L11

A cause de cette ligne, la liste complète des dépendances est loadé dans le bundle webpack et donc disponible à quiconque charge le front, offrant la possibilité de cibler des attaques pour certains packages

import { name, description } from '../../package.json'

**Comment by guillaumeduhan** [comment]
Merci Valdo ! Je vais changer ça
