### ISSUE TITLE
Dependency resolution issue on installation

### ISSUE THREAD

**Issue by anthonybudd** [guillaumeduhan/vue-bootstrap-boilerplate#8]
I am getting a dependency resolution issue when I try to install this project.

Is this a local issue or a issue with the repository?

```sh
$> git clone git@github.com:guillaumeduhan/vue-bootstrap-boilerplate.git
$> cd vue-bootstrap-boilerplate/
$> npm i

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vue-bootstrap-boilerplate@2.0.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.5.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0" from eslint-plugin-vue@5.2.3
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^5.2.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/anthonybudd/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anthonybudd/.npm/_logs/2021-06-06T23_59_40_923Z-debug.log
```

**Comment by ifeLawal** [comment]
I had the same error. It seems to be a known issue that is happening related to node and eslint dependency issues and not this package: https://github.com/npm/cli/issues/2000.

I was able to get ```npm i``` working by using node version 14.13.1 as mentioned in the comments.

**Comment by guillaumeduhan** [comment]
Hello @anthonybudd,

Thank you for your message. As said @ifeLawal (thank you for your answer), it is a known issue related to node & eslint.

If you didn't found any solution, you could also check this post that helps to install localy legacy-peer-deps:
https://stackoverflow.com/questions/64874754/unable-to-resolve-dependency-tree-with-esling-config-airbnb

Best,

Guillaume
